version: '3'

services:
  local-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postresql/data
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge